name: LaTeX Diff

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  perl_operations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.32"
        distribution: strawberry
        install-modules: |
          Algorithm::Diff

    - name: Concatenate LaTeX New Document (Perl script)
      run: perl ./00_Scripts/latexpand.pl main.tex > new.tex

    - name: Run texcount (Perl script)
      run: perl ./00_Scripts/texcount.pl new.tex > count.txt

    - name: Concatenate LaTeX Old Document (Perl script)
      run: |
        git fetch origin main
        git restore --source origin/main main.tex
        perl ./00_Scripts/latexpand.pl main.tex > old.tex

    - name: Generate LaTeX Diff Document (Perl Script)
      run: perl ./00_Scripts/latexdiff.pl old.tex new.tex > diff.tex

    - name: Upload Perl Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: perl-output
        path: |
          new.tex
          diff.tex
          count.txt

  build_pdf:
    runs-on: ubuntu-latest
    needs: perl_operations

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Perl Artifacts
      uses: actions/download-artifact@v3
      with:
        name: perl-output

    - uses: xu-cheng/latex-action@v3
      with:
        root_file: new.tex

    - uses: xu-cheng/latex-action@v3
      with:
        root_file: diff.tex

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pdf-output
        path: |
          new.pdf
          diff.pdf